### ISSUE TITLE
Meeting for progress of the Assignment as well as Selection of the 2nd Open Source project

### ISSUE THREAD

**Issue by mohsinali1051** [SQE-Testers/Assignment_3#4]
Kindly leave a comment when you guys are available for the meeting.

**Comment by mohsinali1051** [comment]
I am available tomorrow after 6 PM.

**Comment by faiqhassan420** [comment]
I am available today and tomorrow at 5pm.

**Comment by mohsinali1051** [comment]
So if @muneebwaqas416 is available tomorrow after 6 PM, then we can have a meeting session.

**Comment by mohsinali1051** [comment]
We all have decided to have a meeting today at 11 PM.
